export const TERMS_AND_CONDITIONS = `
LAST UPDATED: January 22, 2026

1. ACCEPTANCE OF TERMS
By accessing and using Icomly ("the Service"), you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by these terms, please do not use this Service.

2. NATURE OF SERVICE (ENTERTAINMENT PURPOSES ONLY)
Icomly is an automated tracking platform that aggregates publicly available data and uses Artificial Intelligence to generate summaries and location estimates. 
- NO GUARANTEE OF ACCURACY: The Content is generated by AI and may contain errors or outdated information.
- NOT FOR NAVIGATIONAL OR SAFETY USE: You agree not to use location data for navigation, safety, or critical decision-making.
- ENTERTAINMENT ONLY: This tool is strictly for entertainment. We are not a news agency and do not verify the factual accuracy of AI-generated summaries.

3. DISCLAIMER OF WARRANTIES
The Service is provided on an "AS IS" and "AS AVAILABLE" basis. Icomly expressly disclaims all warranties of any kind, whether express or implied.

4. LIMITATION OF LIABILITY
In no event shall Icomly, its owners, directors, or partners be liable for any direct, indirect, or incidental damages resulting from the use of the Service.

5. USER CONDUCT & ANTI-STALKING POLICY
You agree NOT to use the Service to:
- Harass, stalk, threaten, or intimidate any person (celebrity or otherwise).
- Physically locate individuals for the purpose of harm or unwanted contact.
- Gather data for commercial redistribution (scraping).
Violation of this section will result in immediate termination of your account.

6. SUBSCRIPTIONS AND CANCELLATIONS
- "Insider Pro" subscriptions are billed monthly.
- You may cancel at any time via your Profile settings.
- Cancellations take effect at the end of the current billing cycle.

7. INTELLECTUAL PROPERTY
All AI-generated analysis, UI design, and code are the property of Icomly. Celebrity images are sourced via public APIs or are simulated placeholders.

8. GOVERNING LAW
These Terms shall be governed by the laws of the State of Delaware.
`;

export const PRIVACY_POLICY = `
LAST UPDATED: January 22, 2026

1. DATA WE COLLECT
- Account Data: Email address, encrypted password, and name.
- Usage Data: Celebrities you follow and interaction frequency.
- Payment Data: Processed securely via Stripe.

2. HOW WE USE YOUR DATA
- To provide the Service (managing your watchlist).
- To send transactional emails (password resets).
- To send Weekly Digests (if opted-in).

3. DATA PROCESSING & THIRD PARTIES
We share data with the following processors:
- Google Gemini API: For generating summaries.
- Stripe: For payment processing.

4. YOUR RIGHTS
You have the right to access, correct, or delete your personal data at any time via your account settings.
`;
